// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Week12_CodeFirstBasic.Data;

#nullable disable

namespace Week12_CodeFirstBasic.Data.Migrations
{
    [DbContext(typeof(PatikaFirstDbContext))]
    [Migration("20241217202718_Ilk")]
    partial class Ilk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Week12_CodeFirstBasic.Data.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Call Of Duty",
                            Platform = "Bilgisayar",
                            Rating = 8m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Age Of Empires",
                            Platform = "Bilgisayar",
                            Rating = 6m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fruit Ninja",
                            Platform = "Mobile",
                            Rating = 4m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Assasian Creed",
                            Platform = "Xbox",
                            Rating = 9m
                        });
                });

            modelBuilder.Entity("Week12_CodeFirstBasic.Data.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Korku",
                            ReleaseYear = 2002,
                            Title = "Kuzuların Sessizliği"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Aksiyon,BilimKurgu",
                            ReleaseYear = 2000,
                            Title = "Yüzüklerin Efendisi"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Aksiyon",
                            ReleaseYear = 2016,
                            Title = "Dağ2"
                        },
                        new
                        {
                            Id = 4,
                            Genre = "Animasyon",
                            ReleaseYear = 2005,
                            Title = "Buz Devri"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
